In_Mgmt/Models/Location.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel;

namespace In_Mgmt.Models
{
    public class Location
    {
        public int LocationID { get; set; }

        [Required]
        [DisplayName("Location Name:")]
        public string LocationName { get; set; }

        [Required]
        [DisplayName("Location Code:")]
        public string LocationCode { get; set; }
        
        //foreign key
        public int ContainerID { get; set; }
        [DisplayName("Container:")]
        public virtual Container Container { get; set; }
       
    }
}

In_Mgmt/Controllers/ContainersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using In_Mgmt.Models;

namespace In_Mgmt.Controllers
{ 
    public class ContainersController : Controller
    {
        private In_MgmtContext db = new In_MgmtContext();

        //
        // GET: /Containers/

        public ViewResult Index()
        {
            var containers = db.Containers.Include(c => c.UOM);
            return View(containers.ToList());
        }

        //
        // GET: /Containers/Details/5

        public ViewResult Details(int id)
        {
            Container container = db.Containers.Find(id);
            return View(container);
        }

        //
        // GET: /Containers/Create

        public ActionResult Create(int? id)
        {
            var ContainerID = id; //added
            var KPIID = id;
            ViewBag.UOMID = new SelectList(db.UOMs, "UOMID", "UOM_Code");
            return View();
        } 

        //
        // POST: /Containers/Create

        [HttpPost]
        public ActionResult Create(Container container)
        {
            if (ModelState.IsValid)
            {
                db.Containers.Add(container);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            ViewBag.UOMID = new SelectList(db.UOMs, "UOMID", "UOM_Code", container.UOMID);
            return View(container);
        }
        
        //
        // GET: /Containers/Edit/5
 
        public ActionResult Edit(int id)
        {
            Container container = db.Containers.Find(id);
            ViewBag.UOMID = new SelectList(db.UOMs, "UOMID", "UOM_Code", container.UOMID);
            return View(container);
        }

        //
        // POST: /Containers/Edit/5

        [HttpPost]
        public ActionResult Edit(Container container)
        {
            if (ModelState.IsValid)
            {
                db.Entry(container).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.UOMID = new SelectList(db.UOMs, "UOMID", "UOM_Code", container.UOMID);
            return View(container);
        }

        //
        // GET: /Containers/Delete/5
 
        public ActionResult Delete(int id)
        {
            Container container = db.Containers.Find(id);
            return View(container);
        }

        //
        // POST: /Containers/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Container container = db.Containers.Find(id);
            db.Containers.Remove(container);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

In_Mgmt/Controllers/LocationsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using In_Mgmt.Models;

namespace In_Mgmt.Controllers
{ 
    public class LocationsController : Controller
    {
        private In_MgmtContext db = new In_MgmtContext();

        //
        // GET: /Locations/

        public ViewResult Index()
        {
            var locations = db.Locations.Include(l => l.Container);
            return View(locations.ToList());
        }

        //
        // GET: /Locations/Details/5

        public ViewResult Details(int id)
        {
            Location location = db.Locations.Find(id);
            return View(location);
        }

        //
        // GET: /Locations/Create

        public ActionResult Create()
        {
            ViewBag.ContainerID = new SelectList(db.Containers, "ContainerID", "ContainerCode");
            return View();
        } 

        //
        // POST: /Locations/Create

        [HttpPost]
        public ActionResult Create(Location location)
        {
            if (ModelState.IsValid)
            {
                db.Locations.Add(location);
                db.SaveChanges();
                return RedirectToAction("Index");  
            }

            ViewBag.ContainerID = new SelectList(db.Containers, "ContainerID", "ContainerCode", location.ContainerID);
            return View(location);
        }
        
        //
        // GET: /Locations/Edit/5
 
        public ActionResult Edit(int id)
        {
            Location location = db.Locations.Find(id);
            ViewBag.ContainerID = new SelectList(db.Containers, "ContainerID", "ContainerCode", location.ContainerID);
            return View(location);
        }

        //
        // POST: /Locations/Edit/5

        [HttpPost]
        public ActionResult Edit(Location location)
        {
            if (ModelState.IsValid)
            {
                db.Entry(location).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            ViewBag.ContainerID = new SelectList(db.Containers, "ContainerID", "ContainerCode", location.ContainerID);
            return View(location);
        }
                
        //
        // GET: /Locations/Delete/5
 
        public ActionResult Delete(int id)
        {
            Location location = db.Locations.Find(id);
            return View(location);
        }

        //
        // POST: /Locations/Delete/5

        [HttpPost, ActionName("Delete")]
        public ActionResult DeleteConfirmed(int id)
        {            
            Location location = db.Locations.Find(id);
            db.Locations.Remove(location);
            db.SaveChanges();
            return RedirectToAction("Index");
        }
        
        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

In_Mgmt/Views/Locations/Create.cshtml
@model In_Mgmt.Models.Location

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Location</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.LocationName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LocationName)
            @Html.ValidationMessageFor(model => model.LocationName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LocationCode)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LocationCode)
            @Html.ValidationMessageFor(model => model.LocationCode)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ContainerID, "Container")
        </div>
        <div class="editor-field">
            @Html.ListBox("ContainerID")
            @*@Html.DropDownList("ContainerID")*@
            @Html.ValidationMessageFor(model => model.ContainerID)
        </div>

        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

In_Mgmt/Views/Locations/Delete.cshtml
@model In_Mgmt.Models.Location

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Location</legend>

    <div class="display-label">LocationName</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LocationName)
    </div>

    <div class="display-label">LocationCode</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LocationCode)
    </div>

    <div class="display-label">Container</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Container.ContainerCode)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

In_Mgmt/Views/Locations/Details.cshtml
@model In_Mgmt.Models.Location

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<fieldset>
    <legend>Location</legend>

    <div class="display-label">LocationName</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LocationName)
    </div>

    <div class="display-label">LocationCode</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.LocationCode)
    </div>

    <div class="display-label">Container</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.Container.ContainerCode)
    </div>
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.LocationID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

In_Mgmt/Views/Locations/Edit.cshtml
@model In_Mgmt.Models.Location

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Location</legend>

        @Html.HiddenFor(model => model.LocationID)

        <div class="editor-label">
            @Html.LabelFor(model => model.LocationName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LocationName)
            @Html.ValidationMessageFor(model => model.LocationName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.LocationCode)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.LocationCode)
            @Html.ValidationMessageFor(model => model.LocationCode)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ContainerID, "Container")
        </div>
        <div class="editor-field">
            @Html.DropDownList("ContainerID", String.Empty)
            @Html.ValidationMessageFor(model => model.ContainerID)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

In_Mgmt/Views/Locations/Index.cshtml
@model IEnumerable<In_Mgmt.Models.Location>

@{
    ViewBag.Title = "Index";
}

<h2>Location</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            LocationName
        </th>
        <th>
            LocationCode
        </th>
        <th>
            Container
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.LocationName)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.LocationCode)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Container.ContainerCode)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id=item.LocationID }) |
            @Html.ActionLink("Details", "Details", new { id=item.LocationID }) |
            @Html.ActionLink("Delete", "Delete", new { id=item.LocationID }) | 
            @Html.ActionLink("Add Container", "Create", "Containers", new { id = item.LocationID }, null)
         </td>
    </tr>
}

</table>